### ISSUE TITLE
1.108

### ISSUE THREAD

**Issue by bombcheck** [m3talstorm/foe-decryption#5]
New version is out:
BUILD_NUMBER:String = "02f78b4597";
BUILD_TIME:String = "23.08.2017 10:56";
VERSION_SECRET:String = "yOy3qr/HW9NZ9iLXjYLVADMO7wKMZcTgsUVqcqkl+h7ddVER8sHYEH6bxsSJOzerXci2kJKcMM9xQZjmdVD08Q==";
VERSION:String = "1.108";

**Comment by diogofacin** [comment]
Great :)

Not sure if you all are aware, but they usually change their VOs classes, in 1.108 they changed ArmyUnitVO and AbstractUnitVO (as they are also applying static data for units).

I am not using the Foe-Bot because i developed my own solution (in Java), and I have to check their Main.swf source code every update to merge those changes.

Just letting you know that some bots may have some features stop working after their releases.

**Comment by nanakiksc** [comment]
I guess the timestamp is 1503485760. Is that correct? (the BUILD_TIME in Unix time format?).

**Comment by m3talstorm** [comment]
Updated the README
